### ISSUE TITLE
Badge Cannot Be Generated

### ISSUE THREAD

**Issue by indiesquidge** [matthew342/simplecov-badge#2] opened 2015-01-29 21:32 UTC
I could be doing something wrong, but I followed the instructions in the README, installed the prerequisites, gems, and added the code to my test_helper.rb file. Here is my output after `rake test`:
![screen shot 2015-01-29 at 2 28 58 pm](https://cloud.githubusercontent.com/assets/3409645/5966633/6b1d1a52-a7c3-11e4-92f9-c8dfb6d30da8.png)
 
Not exactly sure if this is an issue on Homebrew's ImageMagick's or your side, but I would love any help I can get to make it work. Thanks.

**Comment by matthew342** [comment] 2015-01-30 16:24
Looks like ImageMagick didn't start. Make sure you can run ImageMagick's 'convert' command first.

**Comment by indiesquidge** [comment] 2015-02-01 02:05
Yeah it looks like I can run the commands. Is there something in particular I need to run beforehand?
![screen shot 2015-01-31 at 7 04 50 pm](https://cloud.githubusercontent.com/assets/3409645/5990709/1c9fea0c-a97c-11e4-9e63-82f04c82e6bd.png)

**Comment by matthew342** [comment] 2015-02-01 13:52
What OS are you on? Simplecov-badge is acting like convert is returning a non-zero exit code.

**Comment by indiesquidge** [comment] 2015-02-02 23:18
I'm currently running on OS X Yosemite 10.10.2. Could this be a problem with the OS since it was recently updated from 10.10.1?

**Comment by scarver2** [comment] 2015-02-05 23:02
The issue is the `convert` exits with a 1, not 0, when no parameters are passed to it. 
output = `convert` returns ﻿#<Process::Status: pid 83651 exit 1>

**Comment by matthew342** [comment] 2015-09-25 15:22
Fix merged - thanks @jreinert!

**Closed by matthew342** 2015-09-25 15:22 UTC

**Comment by shadowbq** [comment] 2016-02-10 08:47
Please update and push the gem.
